<%@ taglib uri="/struts-tags" prefix="s" %>
<html>
<head>
    <title>JavaScript JSON</title>

    <script type="text/javascript">
        function loadRemotely() {

            //load dojo RPC
            dojo.require("dojo.rpc.*");

            //create service object(proxy) using SMD (generated by the json result)
            var url = '<s:url namespace="/services/json" action="eventAPI" />';
            var service = new dojo.rpc.JsonService(url);

            //function called when remote method returns
            var callback = function(result) {

                var display="";

                for( var e=0; e<result.length; e++ ){
                    var name = result[e].eventName;
                    var startTime = result[e].startTime;
                    display += "<b>"+name+"</b> - "+startTime+"<br/>";
                }
                dojo.byId("main").innerHTML = display;
            }

            // execute remote method
            service.findRecentEvents(10).addCallback(callback);
        }
    </script>
</head>

<body onload="loadRemotely()"></body>
</html>